# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: pretty-format-json
      exclude: '^(modules/sekai-master-db/.*)'
      args: [--autofix, --no-sort-keys]
    - id: check-json
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: trailing-whitespace
